# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terralint < Formula
  desc "An opinionated terraform linter"
  homepage "https://github.com/vahid-haghighat/terralint"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.2/terralint_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "077daff21294bda229e135d4c98eed3385fb9fd9ce933057d27e46ca87495f8f"

      def install
        bin.install "terralint"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.2/terralint_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b60cd8a8667a6257e0ff6ab43276ba84ff1ed49d92e7e3f9f108ca8f140fb6e"

      def install
        bin.install "terralint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.2/terralint_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "0a19d7175189697b22534381ed9803e8a8c3d3593e427b4bb911a1fd490441fe"

        def install
          bin.install "terralint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.2/terralint_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "cff2fda857a3026430500e5895e10c23969a975a7dc0ac01e6b0780b56b9201c"

        def install
          bin.install "terralint"
        end
      end
    end
  end

  test do
    system "#{bin}/terralint --version"
  end
end
