# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terralint < Formula
  desc "An opinionated terraform linter"
  homepage "https://github.com/vahid-haghighat/terralint"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.1.0/terralint_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "20b4c888a9a2578de1cdf12a96cb3713e380fe16da85c85cbc968ae267f9ac01"

      def install
        bin.install "terralint"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.1.0/terralint_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6bb698a4fd22daf13c9fc84793e5fbd435a94396621d7c574fdc36966a1bcf88"

      def install
        bin.install "terralint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.1.0/terralint_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "97ea91cbaff9c7385ac89083420ece1b433edd0f78c1e6cff6eea975ec78e56a"

        def install
          bin.install "terralint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.1.0/terralint_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "3c3dc8683944268cd6b101665967789d849b9aaf71348d4b03512335621e825f"

        def install
          bin.install "terralint"
        end
      end
    end
  end

  test do
    system "#{bin}/terralint --version"
  end
end
