# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terralint < Formula
  desc "An opinionated terraform linter"
  homepage "https://github.com/vahid-haghighat/terralint"
  version "0.2.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.7/terralint_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "4dc2b2d8c127b8f82eadef2a7545b8f71e5379c72888748f7a97d95389f52f38"

      def install
        bin.install "terralint"
      end
    end
    on_arm do
      url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.7/terralint_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "1705a8c835e7d54303a7d5674d4b2f0f6baf84af8bf4f1ae8defa86c2892e1ad"

      def install
        bin.install "terralint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.7/terralint_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "e4beef6872311f7c44e8e7ba472d5daed5dc25802ffb83238e45e96c6afb1d87"

        def install
          bin.install "terralint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/terralint/releases/download/v0.2.7/terralint_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "36e3675ba770aed32d6ef653164f761f6e63e0ebd35e9fd1f1bb0afe19add743"

        def install
          bin.install "terralint"
        end
      end
    end
  end

  test do
    system "#{bin}/terralint --version"
  end
end
